### ISSUE TITLE
New Rogueapp issue template doesnt include field for Appid

### ISSUE THREAD

**Issue by syne0** [huntresslabs/rogueapps#15]
I noticed that the submission template for the issue doesn't include a field to submit the appid, as far as I can see? Unless it's what's meant by the App Publisher ID. Please advise where/how to communicate the appid when submitting issues for new apps.

Thanks!

**Comment by HuskyHacks** [comment]
Thanks again @syne0 for the submission and raising the question. If a submission provides enough information, I have no issue grabbing the App ID while adding the submission info to the JSON file. I'll add a field for it but I also have no problem just looking it up!

The App Publisher ID in this case is the code for the application publisher. You can usually find that in the app manifest or by enumerating the service principal for the app, which is listed as the verifiedPublisherID:

```json
{
            "id": "5aaf8887-9372-4529-a8ed-3fa0f144f87e",
            "deletedDateTime": null,
            "accountEnabled": true,
            "alternativeNames": [],
            "appDisplayName": "eM Client",
            
           ...[snip]...

               "verifiedPublisher": {
                "displayName": "eM Client s.r.o.",
                "verifiedPublisherId": "5365206",
                "addedDateTime": "2021-01-28T19:12:58Z"
            }
```

**Comment by syne0** [comment]
Oh, I was wondering how to grab that information! Thanks for letting me know..
